# Generated by Django 5.0.7 on 2024-08-01 19:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_duration",
                    models.IntegerField(
                        default=20, help_text="Duration of pdf in seconds"
                    ),
                ),
                (
                    "pdf_name",
                    models.CharField(
                        default="TA100-70020",
                        help_text="Name of PDF file",
                        max_length=100,
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="Pdf_files/")),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("TA100-70020", "TA100-70020"),
                            ("TA100-11050", "TA100-11050"),
                            ("TA100-11051", "TA100-11051"),
                            ("TA100-11052", "TA100-11052"),
                            ("TA100-11053", "TA100-11053"),
                            ("TA100-11054", "TA100-11054"),
                            ("TA100-11055", "TA100-11055"),
                            ("TA100-11056", "TA100-11056"),
                            ("TA100-11057", "TA100-11057"),
                            ("TA100-11058", "TA100-11058"),
                        ],
                        default="TA100-70020",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("RUNNING", "Running"), ("STOPPED", "Stopped")],
                        default="STOPPED",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_duration",
                    models.IntegerField(
                        default=20, help_text="Duration of video in seconds"
                    ),
                ),
                (
                    "video_name",
                    models.CharField(
                        default="TA100-70020",
                        help_text="Name of Media file",
                        max_length=100,
                    ),
                ),
                ("video_file", models.FileField(upload_to="Videos_files/")),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Screen",
            fields=[
                ("screen_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "manager",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screen_app.product",
                    ),
                ),
                (
                    "upload_pdf",
                    models.ManyToManyField(blank=True, to="screen_app.pdffile"),
                ),
                (
                    "upload_video",
                    models.ManyToManyField(blank=True, to="screen_app.videofile"),
                ),
            ],
        ),
    ]
