# Generated by Django 5.0.7 on 2024-08-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdffile",
            name="pdf_file",
            field=models.FileField(upload_to="static/Pdf_files/"),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="video_file",
            field=models.FileField(upload_to="static/Videos_files/"),
        ),
    ]
