# Generated by Django 5.0.7 on 2024-08-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0002_alter_pdffile_pdf_file_alter_videofile_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdffile",
            name="pdf_file",
            field=models.FileField(upload_to="static/media/Pdf_files/"),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="video_file",
            field=models.FileField(upload_to="static/media/Videos_files/"),
        ),
    ]
